
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 23 20:23:32 CET 2022
//----------------------------------------------------

package Pr2b.CUP;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int OP_100 = 28;
  public static final int OP_MAY_IG = 25;
  public static final int OP_MAYOR = 23;
  public static final int SEP_SEC = 13;
  public static final int PCIERRE = 17;
  public static final int SEP_INS = 14;
  public static final int NUM_INT = 2;
  public static final int INT = 37;
  public static final int ARRAY = 48;
  public static final int WRITE = 54;
  public static final int DELETE = 52;
  public static final int OP_DIV = 21;
  public static final int NOT = 6;
  public static final int AND = 4;
  public static final int RECORD = 47;
  public static final int CORCHETE_CIERRE = 30;
  public static final int TYPE = 57;
  public static final int OR = 5;
  public static final int BOOL = 39;
  public static final int CALL = 46;
  public static final int OP_AMP = 36;
  public static final int LLAVE_AP = 31;
  public static final int IF = 10;
  public static final int OP_MEN_IG = 24;
  public static final int ID = 58;
  public static final int ENDWHILE = 45;
  public static final int OF = 49;
  public static final int EOF = 0;
  public static final int TRUE = 40;
  public static final int NEW = 51;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int CADENA = 59;
  public static final int OP_MULT = 20;
  public static final int NULL = 8;
  public static final int OP_RESTA = 19;
  public static final int REAL = 38;
  public static final int PAP = 16;
  public static final int ENDIF = 42;
  public static final int NUM_REAL = 3;
  public static final int ELSE = 12;
  public static final int PUNTO = 33;
  public static final int NL = 55;
  public static final int READ = 53;
  public static final int WHILE = 43;
  public static final int THEN = 11;
  public static final int LLAVE_CIERRE = 32;
  public static final int PROC = 9;
  public static final int OP_FLECHA = 34;
  public static final int STRING = 7;
  public static final int OP_COMP = 26;
  public static final int OP_SUMA = 18;
  public static final int CORCHETE_AP = 29;
  public static final int POINTER = 50;
  public static final int FALSE = 41;
  public static final int VAR = 56;
  public static final int OP_DIST = 27;
  public static final int DO = 44;
  public static final int OP_ASIG = 15;
  public static final int OP_MENOR = 22;
}

