package Pr1a;

public enum ClaseLexica {
	ID, NUM_INT, NUM_REAL, SEP_SEC, SEP_INS, OP_ASIG, PAP, PCIERRE, OP_SUMA, OP_RESTA, OP_MULT, OP_DIV, OP_MENOR,
	OP_MAYOR, OP_MEN_IG, OP_MAY_IG, OP_COMP, OP_DIST, END, INT, REAL, BOOL, TRUE, FALSE, AND, OR, NOT
}
