/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package Pr2b.JavaCC;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int dPos = 2;
  int digito = 3;
  int NumInt = 4;
  int pExp = 5;
  int pDec = 6;
  int NumReal = 7;
  int and = 10;
  int or = 11;
  int not = 12;
  int string = 13;
  int Null = 14;
  int proc = 15;
  int If = 16;
  int then = 17;
  int Else = 18;
  int True = 19;
  int endif = 20;
  int While = 21;
  int Do = 22;
  int endwhile = 23;
  int call = 24;
  int record = 25;
  int Int = 26;
  int real = 27;
  int bool = 28;
  int False = 29;
  int array = 30;
  int of = 31;
  int pointer = 32;
  int New = 33;
  int delete = 34;
  int read = 35;
  int write = 36;
  int nl = 37;
  int var = 38;
  int type = 39;
  int Id = 40;
  int cadena = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<dPos>",
    "<digito>",
    "<NumInt>",
    "<pExp>",
    "<pDec>",
    "<NumReal>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"string\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"false\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<Id>",
    "<cadena>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\"->\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
  };

}
