package Pr1b;

public enum ClaseLexica {
	ID, CADENA, NUM_INT, NUM_REAL, SEP_SEC, SEP_INS, OP_ASIG, PAP, PCIERRE, OP_SUMA, OP_RESTA, OP_MULT, OP_DIV,
	OP_MENOR, OP_MAYOR, OP_MEN_IG, OP_MAY_IG, OP_COMP, OP_DIST, OP_100, CORCHETE_AP, CORCHETE_CIERRE, LLAVE_AP,
	LLAVE_CIERRE, PUNTO, OP_FLECHA, COMA, OP_AMP, END, INT, REAL, BOOL, TRUE, FALSE, AND, OR, NOT, STRING, NULL, PROC, IF,
	THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE, NL, VAR, TYPE
}
