
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Apr 25 13:35:56 CEST 2022
//----------------------------------------------------

package Pr3b.CUP;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int OP_100 = 17;
  public static final int OP_MAY_IG = 14;
  public static final int OP_MAYOR = 12;
  public static final int SEP_SEC = 2;
  public static final int SEP_INS = 3;
  public static final int NUM_INT = 52;
  public static final int INT = 56;
  public static final int ARRAY = 42;
  public static final int WRITE = 48;
  public static final int DELETE = 46;
  public static final int OP_DIV = 10;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int RECORD = 41;
  public static final int CORCHETE_CIERRE = 19;
  public static final int TYPE = 51;
  public static final int OR = 29;
  public static final int BOOL = 58;
  public static final int CALL = 40;
  public static final int OP_AMP = 25;
  public static final int LLAVE_AP = 20;
  public static final int IF = 33;
  public static final int P_CIERRE = 6;
  public static final int OP_MEN_IG = 13;
  public static final int ID = 55;
  public static final int ENDWHILE = 39;
  public static final int OF = 43;
  public static final int EOF = 0;
  public static final int ASIG = 4;
  public static final int TRUE = 26;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CADENA = 54;
  public static final int OP_MULT = 9;
  public static final int NULL = 31;
  public static final int OP_RESTA = 8;
  public static final int REAL = 57;
  public static final int ENDIF = 36;
  public static final int NUM_REAL = 53;
  public static final int ELSE = 35;
  public static final int PUNTO = 22;
  public static final int NL = 49;
  public static final int READ = 47;
  public static final int WHILE = 37;
  public static final int P_AP = 5;
  public static final int THEN = 34;
  public static final int LLAVE_CIERRE = 21;
  public static final int STRING = 59;
  public static final int PROC = 32;
  public static final int OP_FLECHA = 23;
  public static final int OP_COMP = 15;
  public static final int OP_SUMA = 7;
  public static final int CORCHETE_AP = 18;
  public static final int POINTER = 44;
  public static final int FALSE = 27;
  public static final int VAR = 50;
  public static final int OP_DIST = 16;
  public static final int DO = 38;
  public static final int OP_MENOR = 11;
}

