package Pr3b;

import Pr3b.TinyASint.*;

public class ProcesamientoPorDefecto implements Procesamiento {
	public void procesa(Prog_con_decs prog) {}
	public void procesa(Prog_sin_decs prog) {}
	public void procesa(Decs_una decs) {}
	public void procesa(Decs_muchas decs) {}
	public void procesa(Dec_var dec) {}
	public void procesa(Dec_tipo dec) {}
	public void procesa(Dec_proc dec) {}
	public void procesa(Params_uno_f p) {}
	public void procesa(Params_muchos_f p) {}
	public void procesa(Param_f_sin_amp p) {}
	public void procesa(Param_f_con_amp p) {}
	public void procesa(Insts_una insts) {}
	public void procesa(Insts_muchas intss) {}
	public void procesa(Inst_asig inst) {}
	public void procesa(Insts_opc_sin_insts inst) {}
	public void procesa(Insts_opc_con_insts inst) {}
	public void procesa(Inst_ifthen inst) {}
	public void procesa(Inst_ifthenelse inst) {}
	public void procesa(Inst_while inst) {}
	public void procesa(Inst_lectura inst) {}
	public void procesa(Inst_escritura inst) {}
	public void procesa(Inst_new_line inst) {}
	public void procesa(Inst_reserv_mem inst) {}
	public void procesa(Inst_lib_mem inst) {}
	public void procesa(Inst_invoc_proc inst) {}
	public void procesa(Inst_comp inst) {}
	public void procesa(Params_vacio p) {}
	public void procesa(Params_lleno p) {}
	public void procesa(Exprs_una e) {}
	public void procesa(Exprs_muchas e) {}
	public void procesa(Tipo_basico tipo) {}
	public void procesa(Tipo_id tipo) {}
	public void procesa(Tipo_array tipo) {}
	public void procesa(Tipo_registro tipo) {}
	public void procesa(Tipo_puntero tipo) {}
	public void procesa(Campos_uno c) {}
	public void procesa(Campos_muchos c) {}
	public void procesa(Campo c) {}
	public void procesa(Bloque_vacio b) {}
	public void procesa(Bloque_lleno b) {}
	public void procesa(Id exp) {}
	public void procesa(True exp) {}
	public void procesa(False exp) {}
	public void procesa(Sstring exp) {}
	public void procesa(None exp) {}
	public void procesa(Num_int exp) {}
	public void procesa(Num_real exp) {}
	public void procesa(Suma exp) {}
	public void procesa(Resta exp) {}
	public void procesa(And exp) {}
	public void procesa(Or exp) {}
	public void procesa(Mayor exp) {}
	public void procesa(Menor exp) {}
	public void procesa(Mayor_eq exp) {}
	public void procesa(Menor_eq exp) {}
	public void procesa(Comp exp) {}
	public void procesa(Dist exp) {}
	public void procesa(Mul exp) {}
	public void procesa(Div exp) {}
	public void procesa(Mod exp) {}
	public void procesa(Corch exp) {}
	public void procesa(Punto exp) {}
	public void procesa(Flecha exp) {}
	public void procesa(Menos exp) {}
	public void procesa(Not exp) {}
	public void procesa(Asterix exp) {}
	public void procesa(ProgramaAux aux) {}
}
